# Generated by Django 4.0.3 on 2022-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.TextField(db_column='messages', default=''),
        ),
    ]
